// ChatGPT_Chatbot/frontend/react-app/src/App.js
import React, { useEffect, useState } from 'react';

const ChatApp = () => {
  const [inputValue, setInputValue] = useState('');
  const [receivedMessage, setReceivedMessage] = useState('');
  const [socket, setSocket] = useState(null);

  useEffect(() => {
    const newSocket = new WebSocket('ws://localhost:8000/chat');

    newSocket.onopen = () => {
      console.log('WebSocket connection established');
    };

    newSocket.onmessage = (event) => {
      setReceivedMessage(event.data);
      console.log(receivedMessage)
    };

    newSocket.onclose = () => {
      console.log('WebSocket connection closed');
    };

    setSocket(newSocket);

    return () => {
      if (newSocket) {
        newSocket.close();
      }
    };
  }, []);

  const sendMessage = (event) => {
    event.preventDefault();
    if (inputValue) {
      console.log(inputValue)
      socket.send(inputValue);
      setInputValue('');
    }
  };

  return (
    <div>
      <h1>ChatGPT Clone</h1>
      <form onSubmit={sendMessage}>
        <input
          type="text"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          placeholder="Type a message..."
        />
        <button type="submit">Send</button>
      </form>
      <p>{receivedMessage}</p>

    </div>
  );
};

export default ChatApp;

// ChatGPT_Chatbot/frontend/angular-app/src/app/app.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})

export class AppComponent implements OnInit, OnDestroy {
  inputValue: string = '';
  receivedMessage: string = '';
  socket: WebSocket | null = null;

  ngOnInit() {
    this.socket = new WebSocket('ws://localhost:8000/chat');

    this.socket.onopen = () => {
      console.log('WebSocket connection established');
    };

    this.socket.onmessage = (event) => {
      this.receivedMessage = event.data;
      console.log(this.receivedMessage);
    };

    this.socket.onclose = () => {
      console.log('WebSocket connection closed');
    };
  }

  ngOnDestroy() {
    if (this.socket) {
      this.socket.close();
    }
  }

  sendMessage(event: MouseEvent) {
    event.preventDefault();
    if (this.inputValue) {
      // if (!this.socket || this.socket.readyState !== WebSocket.OPEN) {
      //   this.socket = new WebSocket('ws://localhost:8000/chat');

      //   this.socket.onopen = () => {
      //     console.log('WebSocket connection established');
      //     this.socket.send(this.inputValue);
      //     console.log(this.inputValue)
      //   };

      //   this.socket.onmessage = (event) => {
      //     this.receivedMessage = event.data;
      //     console.log(this.receivedMessage);
      //     this.socket.close();
      //   };

      //   this.socket.onclose = () => {
      //     console.log('WebSocket connection closed');
      //   };
      // }
      // else {
      //   this.socket.send(this.inputValue);
      //   console.log(this.inputValue)
      // }
      this.socket.send(this.inputValue);
      console.log(this.inputValue)
      this.inputValue = '';
    }
  }


}
<div>
  <h1>ChatGPT Clone</h1>
  <form (ngSubmit)="sendMessage($event)">
    <input type="text" [(ngModel)]="inputValue" name="inputValue" placeholder="Type a message..." />

    <button type="submit">Send</button>
  </form>
  <p>{{ receivedMessage }}</p>
</div>
